//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProjectForDCT.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestProjectForDCT.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⬅️ Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check status.
        /// </summary>
        internal static string CheckStatus {
            get {
                return ResourceManager.GetString("CheckStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compile status: .
        /// </summary>
        internal static string CompileStatus {
            get {
                return ResourceManager.GetString("CompileStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Csrf token: .
        /// </summary>
        internal static string CsrfToken {
            get {
                return ResourceManager.GetString("CsrfToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string DarkThemeName {
            get {
                return ResourceManager.GetString("DarkThemeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difficult.
        /// </summary>
        internal static string Difficult {
            get {
                return ResourceManager.GetString("Difficult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy.
        /// </summary>
        internal static string Easy {
            get {
                return ResourceManager.GetString("Easy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string EnglishLanguageName {
            get {
                return ResourceManager.GetString("EnglishLanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing....
        /// </summary>
        internal static string Executing {
            get {
                return ResourceManager.GetString("Executing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit code: .
        /// </summary>
        internal static string ExitCode {
            get {
                return ResourceManager.GetString("ExitCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard.
        /// </summary>
        internal static string Hard {
            get {
                return ResourceManager.GetString("Hard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeetCode problems.
        /// </summary>
        internal static string LeetCodeProblems {
            get {
                return ResourceManager.GetString("LeetCodeProblems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string LightThemeName {
            get {
                return ResourceManager.GetString("LightThemeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        internal static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory limit (KB).
        /// </summary>
        internal static string MemoryLimit {
            get {
                return ResourceManager.GetString("MemoryLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory used: .
        /// </summary>
        internal static string MemoryUsed {
            get {
                return ResourceManager.GetString("MemoryUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory Limit Exceeded: Execution used more memory than the allowed limit..
        /// </summary>
        internal static string MLE {
            get {
                return ResourceManager.GetString("MLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NZEC / OTHER: User code stopped due to an unexpected reason..
        /// </summary>
        internal static string NZEC_OTHER {
            get {
                return ResourceManager.GetString("NZEC/OTHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open LeetCode problems.
        /// </summary>
        internal static string OpenLeetCodeProblems {
            get {
                return ResourceManager.GetString("OpenLeetCodeProblems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open sandbox.
        /// </summary>
        internal static string OpenSandbox {
            get {
                return ResourceManager.GetString("OpenSandbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output: .
        /// </summary>
        internal static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid only.
        /// </summary>
        internal static string PaidOnly {
            get {
                return ResourceManager.GetString("PaidOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        internal static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run code.
        /// </summary>
        internal static string RunCode {
            get {
                return ResourceManager.GetString("RunCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session token:.
        /// </summary>
        internal static string SessionToken {
            get {
                return ResourceManager.GetString("SessionToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGABRT: Aborting due to a fatal error..
        /// </summary>
        internal static string SIGABRT {
            get {
                return ResourceManager.GetString("SIGABRT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGBUS: Accessed memory location that has not been physically mapped..
        /// </summary>
        internal static string SIGBUS {
            get {
                return ResourceManager.GetString("SIGBUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGFPE: Division by zero..
        /// </summary>
        internal static string SIGFPE {
            get {
                return ResourceManager.GetString("SIGFPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGSEGV: Invalid memory reference or segmentation fault..
        /// </summary>
        internal static string SIGSEGV {
            get {
                return ResourceManager.GetString("SIGSEGV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGXFSZ: The output file size exceeded the allowed system value..
        /// </summary>
        internal static string SIGXFSZ {
            get {
                return ResourceManager.GetString("SIGXFSZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch language: .
        /// </summary>
        internal static string SwitchLanguage {
            get {
                return ResourceManager.GetString("SwitchLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch theme: .
        /// </summary>
        internal static string SwitchTheme {
            get {
                return ResourceManager.GetString("SwitchTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time limit (Seconds).
        /// </summary>
        internal static string TimeLimit {
            get {
                return ResourceManager.GetString("TimeLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time used: .
        /// </summary>
        internal static string TimeUsed {
            get {
                return ResourceManager.GetString("TimeUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your paid account session details to get access.
        /// </summary>
        internal static string TitleEnteringPersonalData {
            get {
                return ResourceManager.GetString("TitleEnteringPersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Limit Exceeded: Execution took more time than the allowed limit..
        /// </summary>
        internal static string TLE {
            get {
                return ResourceManager.GetString("TLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukrainian.
        /// </summary>
        internal static string UkrainianLanguageName {
            get {
                return ResourceManager.GetString("UkrainianLanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown runtime error..
        /// </summary>
        internal static string URE {
            get {
                return ResourceManager.GetString("URE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown status received..
        /// </summary>
        internal static string USR {
            get {
                return ResourceManager.GetString("USR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
